DROP TABLE WASHING_MACHINE;
CREATE TABLE WASHING_MACHINE (BUILDING varchar(1),FLOOR INTEGER, NUMBERR INTEGER,OUT_OF_ORDER BOOLEAN);

INSERT INTO WASHING_MACHINE (BUILDING, FLOOR, NUMBERR, OUT_OF_ORDER)
    VALUES ('A', 4, 1, TRUE);
INSERT INTO WASHING_MACHINE (BUILDING, FLOOR, NUMBERR, OUT_OF_ORDER)
    VALUES ('A', 4, 2, TRUE);
INSERT INTO WASHING_MACHINE (BUILDING, FLOOR, NUMBERR, OUT_OF_ORDER)
    VALUES ('A', 8, 1, TRUE);
INSERT INTO WASHING_MACHINE (BUILDING, FLOOR, NUMBERR, OUT_OF_ORDER)
    VALUES ('A', 8, 2, FALSE);